### ISSUE TITLE
Support for xray console workgroups

### ISSUE THREAD

**Issue by udaykiran19** [aws/aws-xray-daemon#110]
We are looking on to enable this feature to separate apps by workgroups.
https://docs.aws.amazon.com/xray/latest/devguide/xray-console-groups.html

Is there a way i use config map to provide the workgroup name ? If not any workaround to solve this ?

**Comment by willarmiros** [comment]
Hi @udaykiran19,

There is no configuration needed on the daemon to work with groups. A group is defined by an [X-Ray filter expression](https://docs.aws.amazon.com/xray/latest/devguide/xray-console-filters.html). The expression is defined on the console and represents a group of traces that match that expression. 

If you'd like to have all traces go to a certain group, I'd recommend adding an annotation to all your traces and making the expression based on that annotation's value. This would be done with the SDK, not the daemon. Closing this because the groups feature is unrelated to the daemon.
