### ISSUE TITLE
Definition of "spilling over"

### ISSUE THREAD

**Issue by joehoyle** [aws/aws-xray-daemon#17]
We are seeing a lot of `Spilling over 50 segments` messages in the logs, but it's not that clear what this means. Does this just mean there are > 50 segments in the queue, and they'll be sent next request, or are those segments being dropped entirely and never sent upstream?

**Comment by luluzhao** [comment]
Hello @joehoyle , thank you for contacting us regarding your question and sorry for the late response. Daemon sends out segments to X-Ray backend by batches and one batch can have up to 50 number of segments. By design, one channel can has 20 batches of 50 segments at maximum and by default daemon has 8 channels to make concurrent calls to X-Ray backend. When you see this sentence `Spilling over 50 segments`, it means channel is full of 20 batches and the incoming batch is dropped entirely which will never be sent out to our backend. In order to solve this issue, you could config `concurrency` key in daemon configuration file to increase the number of channels. Please let me know if you have any other questions.

**Comment by joehoyle** [comment]
That's great, thanks @luluzhao

**Comment by JulianRMedina** [comment]
I continue to have this issue regardless of increasing memory and or concurrency. Is there any notion of a DLQ or better way to handle the "dropped" traces? For context I've increased concurrency (32) and memory (4gb) but still see spillage.
