### ISSUE TITLE
I can't connect x-ray console via x-ray daemon by docker

### ISSUE THREAD

**Issue by lethienhoang** [aws/aws-xray-daemon#30]
Dockerfile
`FROM amazonlinux
RUN yum install -y unzip
RUN curl -o daemon.zip https://s3.dualstack.ap-southeast-2.amazonaws.com/aws-xray-assets.ap-southeast-2/xray-daemon/aws-xray-daemon-linux-3.x.zip
RUN unzip daemon.zip && cp xray /usr/bin/xray
ENTRYPOINT ["/usr/bin/xray", "-t", "0.0.0.0:2000", "-b", "0.0.0.0:2000"]
EXPOSE 2000/udp
EXPOSE 2000/tcp
`
...
`docker run \
      --attach STDOUT \
      -v ~/.aws/:/root/.aws/:ro \
      --net=host \
      -e AWS_REGION=ap-southeast-2 \
      --name xray-daemon \
      -p 2000:2000/udp \
      xray-daemon -o`

I have been set up my aws access key and aws secret access key in credential of .aws folder

The result of docker running is 
- HTTP proxy server using x-ray endpoint: HTTPS://xray.ap-southeast-2.amazonaws.com
- Starting proxy http server on 127.0.0.1:2000

Then go to https://xray.ap-southeast-2.amazonaws.com/ on browser and got this error
`<MissingAuthenticationTokenException>
  <Message>Missing Authentication Token</Message>
</MissingAuthenticationTokenException>`

My app is running normally . I still see X-Amzn-Trace-Id: Root=1-5dd25d16-b57eba6c376e7395d1645b16; in header of response but don't push them to x-ray console.

How to fix them. What's wrong in setting up x-ray daemon,.... ? Please help me.
![Test1](https://user-images.githubusercontent.com/45428011/69054481-3912b980-0a3e-11ea-817e-89efc6ed2b81.PNG)
![Test2](https://user-images.githubusercontent.com/45428011/69054511-4e87e380-0a3e-11ea-827b-e46734e5b1e2.PNG)

**Comment by bhautikpip** [comment]
Hi @lethienhoang,

Looks like you have configured aws-xray-daemon correctly. I think aws x-ray endpoint will not be accessible to you because daemon is using that endpoint to send data to x-ray service. I would check back configuration with aws-console again since you are not able to see traces on the console.

Follow up questions from my side

1. You have mentioned that you are able to see traces but not on the x-ray console. Do you see messages like "successfully sent batch of 1 segments" in daemon logs ? 

2. Can you provide more details about how you have configured your application with x-ray SDK ? 

Hope this helps!

**Comment by lethienhoang** [comment]
@bhautikpip thanks for replying 
1. Where is daemon log?
2.
In appsettings. 
 `   "XRay": {
    "DisableXRayTracing": "false",
    "SamplingRuleManifest": "SamplingRules.json",
    "AWSXRayPlugins": "EC2Plugin, ECSPlugin, ElasticBeanstalkPlugin",
    "AwsServiceHandlerManifest": "JSONs\\AWSRequestInfo.json",
    "UseRuntimeErrors": "true",
    "CollectSqlQueries": "false"
  } `

In startup

` 
services.AddTransient<HttpClientXRayTracingHandler>();
services.AddHttpClient(...).AddHttpMessageHandler<HttpClientXRayTracingHandler>();  

 AWSXRayRecorder.InitializeInstance(Configuration);
            AWSSDKHandler.RegisterXRayForAllServices();

app.UseXRay("Kavice.Service");
 `

**Comment by lethienhoang** [comment]
@bhautikpip  I don't see anything in daemon running.(console)

**Comment by lethienhoang** [comment]
Thanks I found solutions but I will ask another quétions

**Comment by Gayatri31** [comment]
@lethienhoang 
I have facing same issue, can you please add your solution here.

**Comment by awssandra** [comment]
@Gayatri31 Can you post your X-Ray Daemon logs? Thanks!

**Comment by Gayatri31** [comment]
Hi @awssandra 
Dockerfile: 
```
FROM amazonlinux
ENV AWS_XRAY_DEBUG_MODE=true
RUN yum install -y unzip
RUN curl -o daemon.zip https://s3.us-east-1.amazonaws.com/aws-xray-assets.us-east-1/xray-daemon/aws-xray-daemon-linux-3.x.zip
RUN unzip daemon.zip && cp xray /usr/bin/xray
ENTRYPOINT ["/usr/bin/xray", "-t", "127.0.0.1:2000", "-b", "127.0.0.1:2000"]
EXPOSE 2000/udp
EXPOSE 2000/tcp
```
command:  `docker run  --attach STDOUT  -v ~/.aws/:/root/.aws/:ro --net=host -e AWS_REGION=us-east-1 --expose 2000 -p 2000:2000/tcp -p 2000:2000/udp xray-daemon -o -l debug`

Logs:
![image](https://user-images.githubusercontent.com/7322383/81400275-5e10fb00-914a-11ea-8e2e-b68e8af69bb7.png)

created an IAM user with permissions: AWSXrayFullAccess, AWSXRayDaemonWriteAccess, AmazonS3FullAccess

I'm running the `cat segment.txt > /dev/udp/127.0.0.1/2000` command and expecting that it should connect the daemon and show the _successfully segment sent_ message but nothing is happening neither ant error nor any successor.
Please suggest me the ways or where I went wrong in setting this up.  so that the data should push to Xray.

segment.txt 
{"format": "json", "version": 1}
{"trace_id": "1-594aed87-ad72e26896b3f9d3a27054bb", "id": "6226467e3f845502", "start_time": 1498082657.37518, "end_time": 1498082695.4042, "name": "test.elasticbeanstalk.com"}

**Comment by bhautikpip** [comment]
Hi @Gayatri31 ,

Installation looks fine by looking at the daemon logs. When I ran(using this `cat segment.txt > /dev/udp/127.0.0.1/2000`) segment.txt provided by you was receiving this error in daemon logs. 

```
2020-05-08T11:50:30-07:00 [Error] Unprocessed segment: {
  ErrorCode: "InvalidTraceId",
  Id: "6226467e3f845502",
  Message: "Invalid segment. ErrorCode: InvalidTraceId"
}
2020-05-08T11:50:30-07:00 [Warn] Batch that contains unprocessed segments
```

Would you mind trying out below segment.txt file and see if you see any logs:
```
{"format": "json", "version": 1}
{"id": "6226467e3f845502", "name": "test.elasticbeanstalk.com", "start_time": 1498082657.37518, "trace_id": "1-5eb58dce-ccc2dd20fab9a82e48e1b354", "end_time": 1498082695.4042}
```

I would also recommend you to try out by sending actual segments and subsegments if your goal is to verify daemon installation is correct.

**Comment by Gayatri31** [comment]
Hi @bhautikpip 
Thanks for responding. 
yes, I'm running daemon locally. Tired the segment.txt file provided by you, but didn't see any new logs. 
My goal is to push data to Xray but initially, I wanted to check whether daemon working fine, so that when I integrate (`AWSXRay.setDaemonAddress('127.0.0.1:2000')`) in my app it should work without any issue.
Is there anything else I have to configure or provide permissions? 

```
AMB01144:Desktop $ cat segment.txt > /dev/udp/127.0.0.1/2000
AMB01144:Desktop $ 
```

```
AMB01144:x-ray-deamon$ docker run  --attach STDOUT  -v ~/.aws/:/root/.aws/:ro --net=host -e AWS_REGION=us-east-1 --expose 2000 -p 2000:2000/tcp -p 2000:2000/udp xray-daemon -o -l debug
WARNING: Published ports are discarded when using host network mode
2020-05-09T01:26:35Z [Info] Initializing AWS X-Ray daemon 3.2.0
2020-05-09T01:26:35Z [Debug] Listening on UDP 127.0.0.1:2000
2020-05-09T01:26:35Z [Info] Using buffer memory limit of 19 MB
2020-05-09T01:26:35Z [Info] 304 segment buffers allocated
2020-05-09T01:26:35Z [Debug] Using proxy address: 
2020-05-09T01:26:35Z [Debug] Fetch region us-east-1 from environment variables
2020-05-09T01:26:35Z [Info] Using region: us-east-1
2020-05-09T01:26:35Z [Debug] ARN of the AWS resource running the daemon: 
2020-05-09T01:26:35Z [Debug] No Metadata set for telemetry records
2020-05-09T01:26:35Z [Debug] Using Endpoint: https://xray.us-east-1.amazonaws.com
2020-05-09T01:26:35Z [Debug] Telemetry initiated
2020-05-09T01:26:35Z [Info] HTTP Proxy server using X-Ray Endpoint : https://xray.us-east-1.amazonaws.com
2020-05-09T01:26:35Z [Debug] Using Endpoint: https://xray.us-east-1.amazonaws.com
2020-05-09T01:26:35Z [Debug] Batch size: 50
2020-05-09T01:26:35Z [Info] Starting proxy http server on 127.0.0.1:2000
2020-05-09T01:27:35Z [Debug] Skipped telemetry data as no segments found
2020-05-09T01:28:35Z [Debug] Skipped telemetry data as no segments found
```

**Comment by srprash** [comment]
Hi @Gayatri31 
Sorry we missed on replying to your question. 
Since your dockerfile has the daemon listening on `127.0.0.1:2000` address, you are able to send trace data to it from within the container. To communicate with the daemon from outside the container, you will need to bind the daemon to `0.0.0.0:2000` ([example dockerfile](https://docs.aws.amazon.com/xray/latest/devguide/xray-daemon-ecs.html#xray-daemon-ecs-build)). Then you will need to set the address of your container running the daemon as value to the `AWS_XRAY_DAEMON_ADDRESS` environment variable on the host/container running your application instrumented with X-Ray SDK.

As for the `UnmarshalError` that you see in the daemon logs, it's for the failure to send the periodic telemetry data to X-Ray service. This failure doesn't impact sending of your trace data in any way. We are aware of this bug and will try to fix it ASAP.

**Comment by zaf187** [comment]
@srprash is there an issue number for the bug? i came across it this morning and couldn't figure out if it was something in my application or something in the sdk. thanks.

**Comment by awssandra** [comment]
Hi zaf187,

This is the issue tracking: https://github.com/aws/aws-xray-daemon/issues/22

**Comment by srprash** [comment]
Hi all,
I'm closing this issue since the original concerned has been answered. As for the `UnmarshalError: failed decoding error message` issue, I have opened a [new one](https://github.com/aws/aws-xray-daemon/issues/107) to track it separately.

Thanks
