### ISSUE TITLE
Feature: Visibility into X-ray tracing libraries for other languages

### ISSUE THREAD

**Issue by jason-riddle** [aws/aws-xray-daemon#60]
Apologies because this is not the correct place for this issue, but wanted to see if the team had any insight on this.

Are there plans to create X-ray tracing libraries for the following languages?

- C++
- Php
- Rust

**Comment by willarmiros** [comment]
Hi @jason-riddle,

AWS X-Ray has been building out support for several languages with our new [AWS Distro for OpenTelemetry](https://aws-otel.github.io/). We aim to support more languages in 2021, so I suggest you open a similar issue in our [OTel community repo](https://github.com/aws-observability/aws-otel-community/issues), since it will have more visibility there. I'll close this issue here since we don't currently have plans to support new languages outside Otel.
