### ISSUE TITLE
EC2 Windows Server - Unable to start service

### ISSUE THREAD

**Issue by arturtadel** [aws/aws-xray-daemon#80]
I'm trying to run X-Ray daemon as a service on AWS EC2 Windows Server but I can't.

I've received the error as below:

`Unable to retrieve the region from the EC2 instance EC2MetadataRequestError: failed to get EC2 instance identity document
caused by: RequestError: send request failed
caused by: Get http://169.254.169.254/latest/dynamic/instance-identity/document: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
`

I've tried to add region to the configuration file but then I see the error: `[Error] Cannot fetch region variable from config file, environment variables and ec2 metadata.`

Finally, I've added new system variable `AWS_REGION` but now I can see another error as below: 

`2020-11-04T15:37:31Z [Error] Get instance id metadata failed: RequestError: send request failed
caused by: Get http://169.254.169.254/latest/meta-data/instance-id: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`

**Comment by srprash** [comment]
Hi @arturtadel 
What version of daemon are you using? Also can you follow [this doc](https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/instancedata-dynamic-data-retrieval.html) and confirm that you're able to access the instance metadata from within your EC2 instance?
Meanwhile, we'll take a look at the daemon code for the issue.

Thanks.

**Comment by arturtadel** [comment]
Hi @srprash,

I'm using version 3.2.0.
unfortunately, I'm not able to take access to metadata from EC2 instance.
I have an error `Invoke-RestMethod : Unable to connect to the remote server` should I change the configuration of this machine?

Thanks!

**Comment by srprash** [comment]
I see. For the XRay daemon to run, it definitely requires the region. The order in which the region is fetched is cli/config file, environment variable, and finally from instance metadata endpoint. If for some reason the instance metadata endpoint is not reachable (its either disabled or daemon is started in local mode), the daemon throws an error which we saw in your case earlier. 
From your last response, it seems like the access to instance metadata is disabled on your EC2 instance. Can you verify the configurations for V1 and V2? You can find more info about it [here](https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/configuring-instance-metadata-service.html#configuring-instance-metadata-options).

One thing that seem odd to me is that the daemon should not fail to start because of error fetching instance id from EC2 metadata. It's only used for telemetry record and the daemon just logs the error in case of this failure. Can you confirm that the daemon doesn't start and you don't see "Starting proxy http server" message in daemon logs? Can you also share complete daemon debug level logs if possible?

Thanks!

**Comment by arturtadel** [comment]
Hi @srprash,

I've checked configuration for V1 and for V2 without any positive results (still with the same error as in my previous comments).
Finally, I've changed the gateway for IP 169.254.169.254 in my route table and now metadata service works fine and I can run the XRay daemon without any errors.

Thanks for your help.
We can close this issue.
